pipeline:

  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: amp-sc-dev

  test:
    image: docker
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    commands:
      - docker run -t --rm amp-sc-dev steamcmd +info +quit

  publish:
      image: spritsail/docker-publish
      when: { branch: [ master ], event: [ push, tag, deployment ] }
      volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
      secrets: [ docker_username, docker_password, microbadger_token ]
      from: amp-sc-dev
      repo: spritsail/amp-steamcmd

  notify:
    image: spritsail/notify
    when: { status: [ success, failure ] }
    secrets: [ webhook_url, notify_token ]
